### ISSUE TITLE
corrupt Checkpoint

### ISSUE THREAD

**Issue by stm233** [paTRICK-swk/P-STMO#31]
Hi, I tried to run P_STMO to test the video in the wild. But when I load the P-STMO's check points, the error message looks like this checkpoint is corrupt.

Traceback (most recent call last):
  File "/home/hongji/Documents/Tianma/pose/video-to-pose3D-master/videopose_PSTMO.py", line 199, in <module>
    inference_video('/home/hongji/Documents/Tianma/pose/video-to-pose3D-master/outputs/kunkun_cut.mp4', 'alpha_pose')
  File "/home/hongji/Documents/Tianma/pose/video-to-pose3D-master/videopose_PSTMO.py", line 195, in inference_video
    main(args)
  File "/home/hongji/Documents/Tianma/pose/video-to-pose3D-master/videopose_PSTMO.py", line 110, in main
    pre_dict = torch.load(no_refine_path)
  File "/home/hongji/miniconda3/envs/STCFormer/lib/python3.8/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/hongji/miniconda3/envs/STCFormer/lib/python3.8/site-packages/torch/serialization.py", line 987, in _legacy_load
    return legacy_load(f)
  File "/home/hongji/miniconda3/envs/STCFormer/lib/python3.8/site-packages/torch/serialization.py", line 884, in legacy_load
    tar.extract('storages', path=tmpdir)
  File "/home/hongji/miniconda3/envs/STCFormer/lib/python3.8/tarfile.py", line 2265, in extract
    tarinfo = self._get_extract_tarinfo(member, filter_function, path)
  File "/home/hongji/miniconda3/envs/STCFormer/lib/python3.8/tarfile.py", line 2272, in _get_extract_tarinfo
    tarinfo = self.getmember(member)
  File "/home/hongji/miniconda3/envs/STCFormer/lib/python3.8/tarfile.py", line 1955, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'storages' not found"

Could you help me to solve this? Is this the checkpoints' problem? I have tried to download two times but it still not work

**Comment by stm233** [comment]
Oh I solve this problem. Maybe the unzip problem in my Ubuntu system. I re-unzip the checkpoints, it works well.
